[WIP] Checkpoint for `offset-prefill`.
Verified the functional and numerical accuracy of `forward_prefill`.
Verified changes to `write_range` to be block-aligned.
General changes throughout to use `block-aligned` start_positions.

Htting an error on `export` that I will need more context for. Although, this seems to be something Rob already warned me about:

```
torch._dynamo.exc.UserError: Constraints violated (32*block, block)! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of 32*block = L['args'][0][0].size()[1] in the specified range 64 <= 32*block <= 2016 are valid because 32*block was inferred to be a constant (64).
  - Not all values of block = L['args'][0][3].size()[1] in the specified range block <= 63 are valid because block was inferred to be a constant (2).
Suggested fixes:
  block = 2
llama2_25m_tinystories/llama_20250701_4.mlir:517:12: error: 'arith.cmpi' op requires all operands to have the same type
    %217 = torch.aten.index.Tensor %199, %216 : !torch.vtensor<[?],si64>, !torch.list<optional<vtensor>> -> !torch.vtensor<[?],si64>
           ^
llama2_25m_tinystories/llama_20250701_4.mlir:517:12: note: see current operation: %7327 = "arith.cmpi"(%arg913, %7326) <{predicate = 2 : i64}> : (i1, i64) -> i1
```